/*@Student name: Phi Long Nguyen
 Student ID: 19247171*/
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/*generate task_file to test
file_name in the task() is generated by this function
structure: task# cpu_burst*/
void generateTaskFile(int m, char* file_name)
{
    int i = 1;
    FILE* task_file = fopen(file_name,"w");
    srand(time(NULL));
    while (i <= m)
    {
        if(i == m)
            fprintf(task_file,"%d %d",i, 1+rand()%50);/*limit at 50seconds burst time*/
        else
            fprintf(task_file,"%d %d\n",i, 1+rand()%50);
        i++;
    }
    fclose(task_file);
}